### ISSUE TITLE
bug from github 20.1

### ISSUE THREAD

**Issue by avigadmaoz** [Cyberark-workato-dev/conjur-authn-k8s-client#45]

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

876

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

876

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

another comment from jira]

**Comment by avigadmaoz** [comment]
from git

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

from Jira
