### ISSUE TITLE
Testing issue creation from GH 178395

### ISSUE THREAD

**Issue by almoko** [Cyberark-workato-dev/conjur-authn-k8s-client#52]
This is the body of the GH issue to be created.

##Bug description
Steps to reproduce:

Current Results:

Expected Results:

Error Messages:

Logs:

Other Symptoms:

Tenant ID / Pod Number:

##

**Comment by maxAtSW** [comment]
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6644

**Comment by almoko** [comment]
creating a comment in GH 
Some text should go into the comment
That's absolutely great!
